#!/usr/bin/python3

from datetime import datetime, date, timedelta
import urllib.request

today = datetime.today()
yesterday = today - timedelta(days=1)
yesterday = (datetime.strftime(yesterday, '%Y-%m-%d'))

URL='https://whoisds.com/whois-database/newly-registered-domains/' + yesterday + '.zip/nrd'

opener = urllib.request.build_opener()
opener.addheaders = [('User-agent', 'Mozilla/5.0 (Windows NT 6.2; Trident/7.0; rv:11.0) like Gecko')]
urllib.request.install_opener(opener)
urllib.request.urlretrieve(URL , yesterday + '.zip')
